export const ADD_DRIVER = "ADD_DRIVER";
export const REMOVE_DRIVER = "REMOVE_DRIVER";
export const FILTER_DRIVERORIGIN = "FILTER_DRIVERORIGIN";
export const FILTER_DRIVERTEAM = "FILTER_DRIVERTEAM";
export const ORDER_DRIVER = "ORDER_DRIVER";
