export const GET_DRIVERS = "GET_DRIVERS";
export const GET_TEAMS = "GET_TEAMS";
export const GET_DRIVERBYNAME = "GET_DRIVERBYNAME";
export const FILTER_ORIGIN = "FILTER_ORIGIN";
export const FILTER_TEAM = "FILTER_TEAM";
export const ORDER_NAME = "ORDER_NAME";
export const ORDER_BIRTHDATE = "ORDER_BIRTHDATE";
