export const GET_DRIVERS = "GET_DRIVERS";
export const FILTER_DRIVERORIGIN = "FILTER_DRIVERORIGIN";
export const FILTER_DRIVERTEAM = "FILTER_DRIVERTEAM";
export const ORDER_DRIVERNAME = "ORDER_DRIVERNAME";
export const ORDER_DRIVERAGE = "ORDER_DRIVERAGE";
